"""empty message

Revision ID: 2ab80084fd79
Revises: 37bf4653cf4d
Create Date: 2020-04-23 17:22:03.733279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab80084fd79'
down_revision = '37bf4653cf4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodic_task', 'expire_seconds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('expire_seconds', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
