"""empty message

Revision ID: 2dea2ae2468d
Revises: ccd1e1f470c2
Create Date: 2020-04-23 14:21:16.152383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dea2ae2468d'
down_revision = 'ccd1e1f470c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_base', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_base', sa.Column('type', sa.SMALLINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
