"""empty message

Revision ID: 37bf4653cf4d
Revises: e9e8dc6a20fd
Create Date: 2020-04-23 16:55:20.659231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bf4653cf4d'
down_revision = 'e9e8dc6a20fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.drop_constraint('periodic_task_model_schedule_fkey', 'periodic_task', type_='foreignkey')
    op.create_foreign_key(None, 'periodic_task', 'schedule_base', ['schedule_id'], ['id'])
    op.drop_column('periodic_task', 'model_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('model_schedule', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'periodic_task', type_='foreignkey')
    op.create_foreign_key('periodic_task_model_schedule_fkey', 'periodic_task', 'schedule_base', ['model_schedule'], ['id'])
    op.drop_column('periodic_task', 'schedule_id')
    # ### end Alembic commands ###
