"""empty message

Revision ID: 7cdae8367b6d
Revises: 
Create Date: 2020-04-23 09:42:56.477537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdae8367b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_tasks',
    sa.Column('ident', sa.SmallInteger(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ident'),
    sa.UniqueConstraint('ident')
    )
    op.create_table('schedule_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clocked_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clocked_time', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crontab_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.String(length=240), nullable=True),
    sa.Column('hour', sa.String(length=96), nullable=True),
    sa.Column('day_of_week', sa.String(length=64), nullable=True),
    sa.Column('day_of_month', sa.String(length=64), nullable=True),
    sa.Column('month_of_year', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interval_schedule',
    sa.Column('period', sa.String(length=24), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['schedule_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodic_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('task', sa.String(length=200), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('kwargs', sa.Text(), nullable=True),
    sa.Column('queue', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=200), nullable=True),
    sa.Column('routing_key', sa.String(length=200), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('expire_seconds', sa.SmallInteger(), nullable=True),
    sa.Column('one_off', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=True),
    sa.Column('date_changed', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_schedule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_schedule'], ['schedule_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('solar_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['schedule_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_schedule')
    op.drop_table('periodic_task')
    op.drop_table('interval_schedule')
    op.drop_table('crontab_schedule')
    op.drop_table('clocked_schedule')
    op.drop_table('schedule_base')
    op.drop_table('periodic_tasks')
    # ### end Alembic commands ###
