"""empty message

Revision ID: 89dbdca040f3
Revises: 74342684fefe
Create Date: 2020-04-24 09:12:17.047884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dbdca040f3'
down_revision = '74342684fefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interval_schedule', sa.Column('every', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interval_schedule', 'every')
    # ### end Alembic commands ###
