"""empty message

Revision ID: bc55961aa175
Revises: 89dbdca040f3
Create Date: 2020-04-24 19:30:28.519727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc55961aa175'
down_revision = '89dbdca040f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('periodic_task_schedule_id_fkey', 'periodic_task', type_='foreignkey')
    op.drop_column('periodic_task', 'schedule_id')
    op.add_column('schedule_base', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule_base', 'periodic_task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_base', type_='foreignkey')
    op.drop_column('schedule_base', 'task_id')
    op.add_column('periodic_task', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('periodic_task_schedule_id_fkey', 'periodic_task', 'schedule_base', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
