"""empty message

Revision ID: beee24c1fa07
Revises: c9fea3c9caba
Create Date: 2020-04-23 18:39:11.329582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beee24c1fa07'
down_revision = 'c9fea3c9caba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodic_task', 'date_changed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('date_changed', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
