"""empty message

Revision ID: c9fea3c9caba
Revises: 2ab80084fd79
Create Date: 2020-04-23 17:22:19.596199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fea3c9caba'
down_revision = '2ab80084fd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodic_task', sa.Column('expire_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodic_task', 'expire_seconds')
    # ### end Alembic commands ###
