"""empty message

Revision ID: ccd1e1f470c2
Revises: 7cdae8367b6d
Create Date: 2020-04-23 14:19:48.147312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd1e1f470c2'
down_revision = '7cdae8367b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'periodic_tasks', ['ident'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'periodic_tasks', type_='unique')
    # ### end Alembic commands ###
