"""empty message

Revision ID: e9e8dc6a20fd
Revises: 2dea2ae2468d
Create Date: 2020-04-23 14:21:42.229656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e8dc6a20fd'
down_revision = '2dea2ae2468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_base', sa.Column('type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_base', 'type')
    # ### end Alembic commands ###
